### ISSUE TITLE
編輯step內容"過長時"需要點選到輸入框的文字段的任何一個位置開始進行編輯, 而不需要每次都要從最後一個字元用backspace到前方

### ISSUE THREAD

**Issue by leechiuhui** [3dw/hackstep#31]
已經在fork完成修改並測試成功,等待審核...........

nextTick(() => {
        // 使用動態ref聚焦到對應的輸入框
        const inputRef = `input-${step.id}`;
        const inputElement = ref(inputRef); **//  inputElement.value.$el.focus();無法使用因為inputElement.value.$el 是undefined**
        if (inputElement.value && inputElement.value.$el) {
          inputElement.value.$el.focus();
        }
      });

const finishEdit = (step) => {
      console.log('end edit!');
      **//step.editing = false; 這行不需要會過快跳出編輯模式或toggleEdit時就失去焦點，因為編輯內容"過長時"需要點選到文字段的任何一個位置開始進行編輯**

      onChange();
      // 可以在這裡添加對step.name的驗證或其他邏輯
    };

**Comment by bestian** [comment]
well done, thanks a lot!!

**Comment by leechiuhui** [comment]
thanks teacher 🐉~~~~~

Bestian Tang ***@***.***>於 2024年4月13日 週六，下午12:23寫道：
